"""baseline_schema

Revision ID: 0044bf4d2561
Revises: 
Create Date: 2026-03-08 13:06:29.760068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0044bf4d2561'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_encriptada', sa.String(length=255), nullable=False),
    sa.Column('nombre_real', sa.String(length=80), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('altura', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('provincia', sa.String(length=40), nullable=True),
    sa.Column('foto_perfil', sa.String(length=500), server_default='default_avatar.png', nullable=False),
    sa.Column('foto_fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_metros', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fecha_eula', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acepta_terminos', sa.Boolean(), nullable=False),
    sa.Column('version_terminos', sa.String(length=10), nullable=False),
    sa.Column('perfil_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('codigo_recuperacion', sa.String(length=64), nullable=True),
    sa.Column('codigo_expiracion', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("codigo_recuperacion IS NULL OR codigo_recuperacion ~* '^[0-9a-f]{64}$'", name='ck_usuarios_codigo_recuperacion_hex64'),
    sa.CheckConstraint("email !~ '[[:space:]]'", name='ck_usuarios_email_no_spaces'),
    sa.CheckConstraint("email ~ '^[^@[:space:]]+@[^@[:space:]]+\\.[^@[:space:]]+$'", name='ck_usuarios_email_basic_format'),
    sa.CheckConstraint("fecha_nacimiento <= (CURRENT_DATE - INTERVAL '18 years')", name='ck_usuarios_fecha_nacimiento_adult'),
    sa.CheckConstraint("genero IS NULL OR genero IN ('Hombre', 'Mujer', 'Otro')", name='ck_usuarios_genero_values'),
    sa.CheckConstraint("nombre_usuario ~ '^[A-Za-z0-9]+$'", name='ck_usuarios_nombre_usuario_alnum'),
    sa.CheckConstraint("provincia IS NULL OR provincia IN ('A Coruña', 'Albacete', 'Alicante', 'Almería', 'Asturias', 'Badajoz', 'Barcelona', 'Burgos', 'Cantabria', 'Castellón', 'Ceuta', 'Ciudad Real', 'Cuenca', 'Cáceres', 'Cádiz', 'Córdoba', 'Girona', 'Granada', 'Guadalajara', 'Guipúzcoa', 'Huelva', 'Huesca', 'Islas Baleares', 'Jaén', 'La Rioja', 'Las Palmas', 'León', 'Lleida', 'Lugo', 'Madrid', 'Melilla', 'Murcia', 'Málaga', 'Navarra', 'Ourense', 'Palencia', 'Pontevedra', 'Salamanca', 'Santa Cruz de Tenerife', 'Segovia', 'Sevilla', 'Soria', 'Tarragona', 'Teruel', 'Toledo', 'Valencia', 'Valladolid', 'Vizcaya', 'Zamora', 'Zaragoza', 'Álava', 'Ávila')", name='ck_usuarios_provincia_values'),
    sa.CheckConstraint('(codigo_recuperacion IS NULL) = (codigo_expiracion IS NULL)', name='ck_usuarios_codigo_recuperacion_pair'),
    sa.CheckConstraint('acepta_terminos IS TRUE', name='ck_usuarios_acepta_terminos_true'),
    sa.CheckConstraint('altura IS NULL OR (altura BETWEEN 50 AND 300)', name='ck_usuarios_altura_range'),
    sa.CheckConstraint('char_length(btrim(foto_perfil)) BETWEEN 1 AND 500', name='ck_usuarios_foto_perfil_len'),
    sa.CheckConstraint('char_length(btrim(password_encriptada)) > 0', name='ck_usuarios_password_hash_non_empty'),
    sa.CheckConstraint('char_length(btrim(version_terminos)) BETWEEN 1 AND 10', name='ck_usuarios_version_terminos_len'),
    sa.CheckConstraint('char_length(email) BETWEEN 3 AND 320', name='ck_usuarios_email_len'),
    sa.CheckConstraint('char_length(nombre_usuario) BETWEEN 5 AND 50', name='ck_usuarios_nombre_usuario_len'),
    sa.CheckConstraint('email = lower(btrim(email))', name='ck_usuarios_email_normalized_lower'),
    sa.CheckConstraint('fecha_nacimiento <= CURRENT_DATE', name='ck_usuarios_fecha_nacimiento_not_future'),
    sa.CheckConstraint('nombre_real IS NULL OR char_length(btrim(nombre_real)) BETWEEN 3 AND 80', name='ck_usuarios_nombre_real_len'),
    sa.CheckConstraint('peso IS NULL OR (peso BETWEEN 20 AND 300)', name='ck_usuarios_peso_range'),
    sa.CheckConstraint('total_metros >= 0', name='ck_usuarios_total_metros_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_total_metros'), 'usuarios', ['total_metros'], unique=False)
    op.create_index('uq_usuarios_email_lower', 'usuarios', [sa.literal_column('lower(email)')], unique=True)
    op.create_index('uq_usuarios_nombre_usuario_lower', 'usuarios', [sa.literal_column('lower(nombre_usuario)')], unique=True)
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('distancia', sa.Integer(), nullable=False),
    sa.Column('duracion', sa.Integer(), nullable=False),
    sa.Column('calorias_quemadas', sa.Integer(), nullable=False),
    sa.Column('ruta_polilinea', sa.Text(), nullable=True),
    sa.Column('ruta_mapa_url', sa.String(length=2048), nullable=True),
    sa.Column('fecha_ruta', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("ruta_mapa_url IS NULL OR ruta_mapa_url ~* '^https?://'", name='ck_actividades_ruta_mapa_url_http'),
    sa.CheckConstraint("tipo IN ('Caminar', 'Correr')", name='ck_actividades_tipo_values'),
    sa.CheckConstraint('calorias_quemadas > 0 AND calorias_quemadas <= 10000', name='ck_actividades_calorias_range'),
    sa.CheckConstraint('distancia > 0 AND distancia <= 300000', name='ck_actividades_distancia_range'),
    sa.CheckConstraint('duracion > 0 AND duracion <= 86400', name='ck_actividades_duracion_range'),
    sa.CheckConstraint('ruta_mapa_url IS NULL OR char_length(ruta_mapa_url) <= 2048', name='ck_actividades_ruta_mapa_url_len'),
    sa.CheckConstraint('ruta_polilinea IS NULL OR char_length(ruta_polilinea) >= 5', name='ck_actividades_ruta_polilinea_len'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actividades_fecha_ruta'), 'actividades', ['fecha_ruta'], unique=False)
    op.create_index('ix_actividades_usuario_fecha', 'actividades', ['usuario_id', 'fecha_ruta', 'id'], unique=False)
    op.create_index(op.f('ix_actividades_usuario_id'), 'actividades', ['usuario_id'], unique=False)
    op.create_table('sesiones_refresh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('familia_id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('ultimo_uso_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revocada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reemplazada_por_jti', sa.String(length=64), nullable=True),
    sa.CheckConstraint("token_hash ~* '^[0-9a-f]{64}$'", name='ck_sesiones_refresh_token_hash_hex64'),
    sa.CheckConstraint('char_length(btrim(familia_id)) BETWEEN 1 AND 64', name='ck_sesiones_refresh_familia_non_empty'),
    sa.CheckConstraint('char_length(btrim(jti)) BETWEEN 1 AND 64', name='ck_sesiones_refresh_jti_non_empty'),
    sa.CheckConstraint('expira_en >= creada_en', name='ck_sesiones_refresh_expira_ge_creada'),
    sa.CheckConstraint('reemplazada_por_jti IS NULL OR char_length(btrim(reemplazada_por_jti)) BETWEEN 1 AND 64', name='ck_sesiones_refresh_reemplazada_por_jti_len'),
    sa.CheckConstraint('revocada_en IS NULL OR revocada_en >= creada_en', name='ck_sesiones_refresh_revocada_ge_creada'),
    sa.CheckConstraint('ultimo_uso_en IS NULL OR ultimo_uso_en >= creada_en', name='ck_sesiones_refresh_ultimo_uso_ge_creada'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesiones_refresh_expira_en'), 'sesiones_refresh', ['expira_en'], unique=False)
    op.create_index(op.f('ix_sesiones_refresh_familia_id'), 'sesiones_refresh', ['familia_id'], unique=False)
    op.create_index(op.f('ix_sesiones_refresh_jti'), 'sesiones_refresh', ['jti'], unique=True)
    op.create_index(op.f('ix_sesiones_refresh_revocada_en'), 'sesiones_refresh', ['revocada_en'], unique=False)
    op.create_index(op.f('ix_sesiones_refresh_usuario_id'), 'sesiones_refresh', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sesiones_refresh_usuario_id'), table_name='sesiones_refresh')
    op.drop_index(op.f('ix_sesiones_refresh_revocada_en'), table_name='sesiones_refresh')
    op.drop_index(op.f('ix_sesiones_refresh_jti'), table_name='sesiones_refresh')
    op.drop_index(op.f('ix_sesiones_refresh_familia_id'), table_name='sesiones_refresh')
    op.drop_index(op.f('ix_sesiones_refresh_expira_en'), table_name='sesiones_refresh')
    op.drop_table('sesiones_refresh')
    op.drop_index(op.f('ix_actividades_usuario_id'), table_name='actividades')
    op.drop_index('ix_actividades_usuario_fecha', table_name='actividades')
    op.drop_index(op.f('ix_actividades_fecha_ruta'), table_name='actividades')
    op.drop_table('actividades')
    op.drop_index('uq_usuarios_nombre_usuario_lower', table_name='usuarios')
    op.drop_index('uq_usuarios_email_lower', table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_total_metros'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
