"""add_total_duracion_total_actividades

Revision ID: 65e153f8fc93
Revises: b124b6549dcf
Create Date: 2026-03-20 18:15:52.950475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65e153f8fc93'
down_revision: Union[str, Sequence[str], None] = 'b124b6549dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actividades', sa.Column('duracion_total',
                  sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('actividades', sa.Column('duracion_movimiento',
                  sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('actividades', sa.Column('duracion_parado',
                  sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('actividades', sa.Column('duracion_pausa_manual',
                  sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('actividades', sa.Column('ritmo_medio_movimiento',
                  sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('actividades', sa.Column('ritmo_medio_total',
                  sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('actividades', sa.Column('velocidad_media_x100',
                  sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('actividades', sa.Column('velocidad_max_x100',
                  sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('actividades', sa.Column(
        'auto_pausas', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('actividades', sa.Column('pausas_manuales',
                  sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('actividades', sa.Column('alertas_velocidad',
                  sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.drop_column('actividades', 'duracion')
    op.add_column('usuarios', sa.Column('total_duracion_segundos',
                  sa.BigInteger(), server_default=sa.text('0'), nullable=False))
    op.add_column('usuarios', sa.Column('total_actividades',
                  sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'total_actividades')
    op.drop_column('usuarios', 'total_duracion_segundos')
    op.add_column('actividades', sa.Column(
        'duracion', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('actividades', 'alertas_velocidad')
    op.drop_column('actividades', 'pausas_manuales')
    op.drop_column('actividades', 'auto_pausas')
    op.drop_column('actividades', 'velocidad_max_x100')
    op.drop_column('actividades', 'velocidad_media_x100')
    op.drop_column('actividades', 'ritmo_medio_total')
    op.drop_column('actividades', 'ritmo_medio_movimiento')
    op.drop_column('actividades', 'duracion_pausa_manual')
    op.drop_column('actividades', 'duracion_parado')
    op.drop_column('actividades', 'duracion_movimiento')
    op.drop_column('actividades', 'duracion_total')
    # ### end Alembic commands ###
