"""baseline schema

Revision ID: 6d34895f53c4
Revises: 
Create Date: 2026-03-07 14:08:29.357204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d34895f53c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_encriptada', sa.String(), nullable=False),
    sa.Column('nombre_real', sa.String(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('genero', sa.String(), nullable=True),
    sa.Column('altura', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('provincia', sa.String(), nullable=True),
    sa.Column('foto_perfil', sa.String(), server_default='default_avatar.png', nullable=False),
    sa.Column('total_metros', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fecha_eula', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acepta_terminos', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('version_terminos', sa.String(length=10), nullable=True),
    sa.Column('perfil_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('codigo_recuperacion', sa.String(length=64), nullable=True),
    sa.Column('codigo_expiracion', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_total_metros'), 'usuarios', ['total_metros'], unique=False)
    op.create_index('uq_usuarios_email_lower', 'usuarios', [sa.literal_column('lower(email)')], unique=True)
    op.create_index('uq_usuarios_nombre_usuario_lower', 'usuarios', [sa.literal_column('lower(nombre_usuario)')], unique=True)
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('distancia', sa.Integer(), nullable=False),
    sa.Column('duracion', sa.Integer(), nullable=False),
    sa.Column('calorias_quemadas', sa.Integer(), nullable=False),
    sa.Column('ruta_polilinea', sa.Text(), nullable=True),
    sa.Column('ruta_mapa_url', sa.Text(), nullable=True),
    sa.Column('fecha_ruta', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('ruta_mapa_url IS NULL OR char_length(ruta_mapa_url) <= 2048', name='ck_actividades_ruta_mapa_url_len'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actividades_fecha_ruta'), 'actividades', ['fecha_ruta'], unique=False)
    op.create_index('ix_actividades_usuario_fecha', 'actividades', ['usuario_id', 'fecha_ruta', 'id'], unique=False)
    op.create_index(op.f('ix_actividades_usuario_id'), 'actividades', ['usuario_id'], unique=False)
    op.create_table('sesiones_refresh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('familia_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('ultimo_uso_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revocada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reemplazada_por_jti', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesiones_refresh_expira_en'), 'sesiones_refresh', ['expira_en'], unique=False)
    op.create_index(op.f('ix_sesiones_refresh_familia_id'), 'sesiones_refresh', ['familia_id'], unique=False)
    op.create_index(op.f('ix_sesiones_refresh_jti'), 'sesiones_refresh', ['jti'], unique=True)
    op.create_index(op.f('ix_sesiones_refresh_revocada_en'), 'sesiones_refresh', ['revocada_en'], unique=False)
    op.create_index(op.f('ix_sesiones_refresh_usuario_id'), 'sesiones_refresh', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sesiones_refresh_usuario_id'), table_name='sesiones_refresh')
    op.drop_index(op.f('ix_sesiones_refresh_revocada_en'), table_name='sesiones_refresh')
    op.drop_index(op.f('ix_sesiones_refresh_jti'), table_name='sesiones_refresh')
    op.drop_index(op.f('ix_sesiones_refresh_familia_id'), table_name='sesiones_refresh')
    op.drop_index(op.f('ix_sesiones_refresh_expira_en'), table_name='sesiones_refresh')
    op.drop_table('sesiones_refresh')
    op.drop_index(op.f('ix_actividades_usuario_id'), table_name='actividades')
    op.drop_index('ix_actividades_usuario_fecha', table_name='actividades')
    op.drop_index(op.f('ix_actividades_fecha_ruta'), table_name='actividades')
    op.drop_table('actividades')
    op.drop_index('uq_usuarios_nombre_usuario_lower', table_name='usuarios')
    op.drop_index('uq_usuarios_email_lower', table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_total_metros'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
